### ISSUE TITLE
Exception: Adding merged_table.ipac to the commit failed.

### ISSUE THREAD

**Issue by keflavich** [camelot-project/frontend#37]
```
Traceback (most recent call last):
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/adam/repos/camelot_frontend/upload_form.py", line 336, in set_columns
    branch,timestamp = commit_change_to_database(username)
  File "/Users/adam/repos/camelot_frontend/upload_form.py", line 374, in commit_change_to_database
    raise Exception("Adding {tablename} to the commit failed.".format(tablename=tablename))
Exception: Adding merged_table.ipac to the commit failed.
```

**Comment by jimdale** [comment]
Me too :(

**Comment by scog1234** [comment]
I get the same problem

**Comment by snlongmore** [comment]
Same here :-1:

**Comment by saci86** [comment]
I got the same.... :(

**Comment by keflavich** [comment]
Probably solved now.  Raise a fresh issue if this comes up again.
